#pragma once

#define LINE_FLAGS_BLOCK_PLAYER_AND_MONSTERS 0x0001
#define LINE_FLAGS_BLOCK_MONSTERS 0x0002
#define LINE_FLAGS_TWO_SIDED 0x0004
#define LINE_FLAGS_UPPER_UNPEGGED 0x0008
#define LINE_FLAGS_LOWER_UNPEGGED 0x0010
#define LINE_FLAGS_SECRET 0x0020
#define LINE_FLAGS_BLOCK_SOUND 0x0040
#define LINE_FLAGS_NEVER_SHOW_AUTOMAP 0x0080
#define LINE_FLAGS_ALWAYS_SHOW_AUTOMAP 0x0100

#define SECTOR_TYPE_NORMAL 0
#define SECTOR_TYPE_BLINK_RANDOM 1 // Blink random
#define SECTOR_TYPE_BLINK_2FPS 2 // Blink 0.5 second
#define SECTOR_TYPE_BLINK_1FPS 3 // Blink 1.0 second
#define SECTOR_TYPE_BOTH 4 // 20% damage per second plus light blink 0.5 second
#define SECTOR_TYPE_DAMAGE_10 5 // 10% damage per second
#define SECTOR_TYPE_DAMAGE_5 7 // 5% damage per second
#define SECTOR_TYPE_OSCILLATE 8 // Oscillates
#define SECTOR_TYPE_SECRET 9 // Player entering this sector gets credit for finding a secret
#define SECTOR_TYPE_DOOR_30 10 // 30 seconds after level start, ceiling closes like a door
#define SECTOR_TYPE_END 11 // Cancels God Mode, 20% damage per second. When player dies, level ends
#define SECTOR_TYPE_BLINK_2FPS_SYNC 12 // Blink 0.5 second, synchronized
#define SECTOR_TYPE_BLINK_1FPS_SYNC 13 // Blink 1.0 second, synchronized
#define SECTOR_TYPE_DOOR_300 14 // 300 seconds after level start, ceiling opens like a door
#define SECTOR_TYPE_DAMAGE_20 16 // 20% damage per second
#define SECTOR_TYPE_FLICKER 17 // Flickers randomly

#define THING_FLAG_EASY 0x0001 // Thing is on skill levels 1 & 2
#define THING_FLAG_MEDIUM 0x0002 // Thing is on skill level 3
#define THING_FLAG_HARD 0x0004 // Thing is on skill levels 4 & 5
#define THING_FLAG_DEAF 0x0008 // Thing is deaf
#define THING_FLAG_MP_ONLY 0x0010 // Thing is not in single player

// Those are doom's types. We use Doom Builder so the types are those of dooms, but we convert to whatever it is in this game. We try to be relative.
#define THING_TYPE_BERSERK 2023
#define THING_TYPE_MAP 2026
#define THING_TYPE_HEALTH_BONUS 2014
#define THING_TYPE_INVISIBILITY 2024
#define THING_TYPE_INVULNERABILITY 2022
#define THING_TYPE_NIGHT_VISION 2045
#define THING_TYPE_MEGA_HEALTH 2013
#define THING_TYPE_ARMOR_BONUS 2015

#define THING_TYPE_BACKPACK 8
#define THING_TYPE_BLUE_ARMOR 2019
#define THING_TYPE_GREEN_ARMOR 2018
#define THING_TYPE_MEDIKIT 2012
#define THING_TYPE_RADIATION_SUIT 2025
#define THING_TYPE_STIMPACK 2011

#define THING_TYPE_BFG_9000 2006
#define THING_TYPE_CHAINGUN 2002
#define THING_TYPE_CHAINSAW 2005
#define THING_TYPE_PLASMA_RIFLE 2004
#define THING_TYPE_ROCKET_LAUNCHER 2003
#define THING_TYPE_SHOTGUN 2001

#define THING_TYPE_AMMO_CLIP 2007
#define THING_TYPE_BOX_OF_AMMO 2048
#define THING_TYPE_BOX_OF_ROCKETS 2046
#define THING_TYPE_BOX_OF_SHELLS 2049
#define THING_TYPE_CELL_CHARGE 2047
#define THING_TYPE_CELL_CHARGE_PACK 17
#define THING_TYPE_ROCKET 2010
#define THING_TYPE_SHOTGUN_SHELLS 2008

#define THING_TYPE_BLUE_KEYCARD 5
#define THING_TYPE_BLUE_SKULL_KEY 40
#define THING_TYPE_RED_KEYCARD 13
#define THING_TYPE_RED_SKULL_KEY 38
#define THING_TYPE_YELLOW_KEYCARD 6
#define THING_TYPE_YELLOW_SKULL_KEY 39

#define THING_TYPE_ARACHNOTRON 68 // D2
#define THING_TYPE_ARCH_VILLE 64 // D2
#define THING_TYPE_BARON_OF_HELL 3003
#define THING_TYPE_CACODEMON 3005
#define THING_TYPE_HEAVY_WEAPON_DUDE 65 // D2
#define THING_TYPE_COMMANDER_KEEN 72 // D2
#define THING_TYPE_CYBERDEMON 16
#define THING_TYPE_DEMON 3002
#define THING_TYPE_ZOMBIEMAN 3004
#define THING_TYPE_SHOTGUN_GUY 9
#define THING_TYPE_HELL_KNIGTH 69 // D2
#define THING_TYPE_IMP 3001
#define THING_TYPE_LOST_SOUL 3006
#define THING_TYPE_MANCUBUS 67 // D2
#define THING_TYPE_PAIN_ELEMENTAL 71 // D2
#define THING_TYPE_REVENANT 66 // D2
#define THING_TYPE_SPECTRE 58
#define THING_TYPE_SPIDER_MASTERMIND 7
#define THING_TYPE_WOLFENSTEIN_SS 84 // D2

#define THING_TYPE_BARREL 2035
#define THING_TYPE_BURNING_BARREL 70 // D2
#define THING_TYPE_BURTN_TREE 43
#define THING_TYPE_CANDELABRA 35
#define THING_TYPE_EVIL_EYE 41
#define THING_TYPE_SHISH_KEBAB 28
#define THING_TYPE_FLOATING_SKULL 42
#define THING_TYPE_FLOOR_LAMP 2028
#define THING_TYPE_HANGING_LEG 53
#define THING_TYPE_HANGING_PAIR_OF_LEGS 52
#define THING_TYPE_HANGING_TORSO_BRAIN_REMOVED 78 // D2
#define THING_TYPE_HANGING_TORSO_LOOKING_DOWN 75 // D2
#define THING_TYPE_HANGING_TORSO_LOOKING_UP 77 // D2
#define THING_TYPE_HANGING_TORSO_OPEN_SKULL 76 // D2
#define THING_TYPE_HANGING_VICTIM_ARMS_OUT 50
#define THING_TYPE_HANGING_VICTIM_GUTS_AND_BRAIN_REMOVED 74 // D2
#define THING_TYPE_HANGING_VICTIM_GUTS_REMOVED 73 // D2
#define THING_TYPE_HANGING_VICTIM_ONE_LEGGED 51
#define THING_TYPE_HANGING_VICTIM_TWITCHING 49
#define THING_TYPE_IMPALED_HUMAN 25
#define THING_TYPE_LARGE_BRONW_TREE 54
#define THING_TYPE_PILE_OF_SULLS_AND_CANDLES 29
#define THING_TYPE_SHORT_BLUE_FIRESTICK 55
#define THING_TYPE_SHORT_GREEN_FIRESTICK 56
#define THING_TYPE_SHORT_GREEN_PILLAR 31
#define THING_TYPE_SHORT_GREEN_PILLAR_WITH_BEATING_HEART 36
#define THING_TYPE_SHORT_RED_FIRESTICK 57
#define THING_TYPE_SHORT_RED_PILLAR 33
#define THING_TYPE_SHORT_RED_PILLAR_WITH_SKULL 37
#define THING_TYPE_SHORT_TECHNO_FLOOR_LAMP 86 // D2
#define THING_TYPE_SKULL_ON_A_POLE 27
#define THING_TYPE_STALAGMITE 47
#define THING_TYPE_TALL_BLUE_FIRESTICK 44
#define THING_TYPE_TALL_GREEN_FIRESTICK 45
#define THING_TYPE_TALL_GREEN_PILLAR 30
#define THING_TYPE_TALL_RED_FIRESTICK 46
#define THING_TYPE_TALL_RED_PILLAR 32
#define THING_TYPE_TALL_TECHNO_FLOOR_LAMP 85 // D2
#define THING_TYPE_TALL_TECHNO_PILLAR 48
#define THING_TYPE_TWITCHING_IMPALED_HUMAN 26

#define THING_TYPE_BLOODY_MESS 10
#define THING_TYPE_BLOODY_MESS2 12
#define THING_TYPE_CANDLE 34
#define THING_TYPE_DEAD_CACODEMON 22
#define THING_TYPE_DEAD_DEMON 21
#define THING_TYPE_DEAD_FORMER_HUMAN 18
#define THING_TYPE_DEAD_FORMER_SERGEANT 19
#define THING_TYPE_DEAD_IMP 20
#define THING_TYPE_DEAD_LOST_SOUL 23 // Invisible
#define THING_TYPE_DEAD_PLAYER 15
#define THING_TYPE_HANGING_LEG_DECO 62
#define THING_TYPE_HANGING_PAIR_OF_LEGS_DECO 60
#define THING_TYPE_HANGING_VICTIM_ARMS_OUT_DECO 59
#define THING_TYPE_HANGING_VICTIM_ONE_LEGGED_DECO 61
#define THING_TYPE_HANGING_VICTIM_TWITCHING_DECO 63
#define THING_TYPE_POOL_OF_BLOOD 79 // D2
#define THING_TYPE_POOL_OF_BLOOD2 80 // D2
#define THING_TYPE_POOL_OF_BLOOD_AND_FLESH 24
#define THING_TYPE_POOL_OF_BRAINS 81 // D2

#define THING_TYPE_BOSS_BRAIN 88 // D2
#define THING_TYPE_DEATHMATCH_START 11
#define THING_TYPE_PLAYER1_START 1
#define THING_TYPE_PLAYER2_START 2
#define THING_TYPE_PLAYER3_START 3
#define THING_TYPE_PLAYER4_START 4
#define THING_TYPE_SPAWN_SHOOTER 89 // D2
#define THING_TYPE_SPAWN_SPOT 87 // D2
#define THING_TYPE_TELEPORT_LANDING 14

//---- LINE TYPES ----
#define LT_NONE 0

// Doors types
#define LT_DR_DOOR_OPEN_WAIT_CLOSE_ALSO_MONSTERS 1
#define LT_DR_DOOR_OPEN_WAIT_CLOSE_FAST 117
#define LT_SR_DOOR_OPEN_WAIT_CLOSE 63
#define LT_SR_DOOR_OPEN_WAIT_CLOSE_FAST 114
#define LT_S1_DOOR_OPEN_WAIT_CLOSE 29
#define LT_S1_DOOR_OPEN_WAIT_CLOSE_FAST 111
#define LT_WR_DOOR_OPEN_WAIT_CLOSE 90
#define LT_WR_DOOR_OPEN_WAIT_CLOSE_FAST 105
#define LT_W1_DOOR_OPEN_WAIT_CLOSE_ALSO_MONSTERS 4
#define LT_W1_DOOR_OPEN_WAIT_CLOSE_FAST 108
#define LT_D1_DOOR_OPEN_STAY 31
#define LT_D1_DOOR_OPEN_STAY_FAST 118
#define LT_SR_DOOR_OPEN_STAY 61
#define LT_SR_DOOR_OPEN_STAY_FAST 115
#define LT_S1_DOOR_OPEN_STAY 103
#define LT_S1_DOOR_OPEN_STAY_FAST 112
#define LT_WR_DOOR_OPEN_STAY 86
#define LT_WR_DOOR_OPEN_STAY_FAST 106
#define LT_W1_DOOR_OPEN_STAY 2
#define LT_W1_DOOR_OPEN_STAY_FAST 109
#define LT_GR_DOOR_OPEN_STAY 46
#define LT_SR_DOOR_CLOSE_STAY 42
#define LT_SR_DOOR_CLOSE_STAY_FAST 116
#define LT_S1_DOOR_CLOSE_STAY 50
#define LT_S1_DOOR_CLOSE_STAY_FAST 113
#define LT_WR_DOOR_CLOSE_STAY 75
#define LT_WR_DOOR_CLOSE_STAY_FAST 107
#define LT_W1_DOOR_CLOSE_STAY 3
#define LT_W1_DOOR_CLOSE_FAST 110
#define LT_WR_DOOR_CLOSE_STAY_OPEN 76
#define LT_W1_DOOR_CLOSE_WAIT_OPEN 16

// Locked door types
#define LT_DR_DOOR_BLUE_OPEN_WAIT_CLOSE 26
#define LT_DR_DOOR_RED_OPEN_WAIT_CLOSE 28
#define LT_DR_DOOR_YELLOW_OPEN_WAIT_CLOSE 27
#define LT_D1_DOOR_BLUE_OPEN_STAY 32
#define LT_D1_DOOR_RED_OPEN_STAY 33
#define LT_D1_DOOR_YELLOW_OPEN_STAY 34
#define LT_SR_DOOR_BLUE_OPEN_STAY_FAST 99
#define LT_SR_DOOR_RED_OPEN_STAY_FAST 134
#define LT_SR_DOOR_YELLOW_OPEN_STAY_FAST 136
#define LT_S1_DOOR_BLUE_OPEN_STAY_FAST 133
#define LT_S1_DOOR_RED_OPEN_STAY_FAST 135
#define LT_S1_DOOR_YELLOW_OPEN_STAY_FAST 137

// Floor types
#define LT_SR_FLOOR_LOWER_TO_LOWEST_FLOOR 60
#define LT_S1_FLOOR_LOWER_TO_LOWEST_FLOOR 23
#define LT_WR_FLOOR_LOWER_TO_LOWEST_FLOOR 82
#define LT_W1_FLOOR_LOWER_TO_LOWEST_FLOOR 38
#define LT_WR_FLOOR_LOWER_TO_LOWEST_FLOOR_CHANGES_TEXTURE 84
#define LT_W1_FLOOR_LOWER_BY_LOWEST_FLOOR_CHANGES_TEXTURE 37
#define LT_SR_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR 69
#define LT_S1_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR 18
#define LT_WR_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR 128
#define LT_W1_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR 119
#define LT_SR_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_FAST 132
#define LT_S1_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_FAST 131
#define LT_WR_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_FAST 129
#define LT_W1_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_FAST 130
#define LT_SR_FLOOR_RAISE_TO_LOWEST_CEILING 64
#define LT_S1_FLOOR_RAISE_TO_LOWEST_CEILING 101
#define LT_WR_FLOOR_RAISE_TO_LOWEST_CEILING 91
#define LT_W1_FLOOR_RAISE_TO_LOWEST_CEILING 5
#define LT_G1_FLOOR_RAISE_TO_LOWEST_CEILING 24
#define LT_SR_FLOOR_RAISE_TO_8_BELLOW_LOWEST_CEILING_CRUSHES 65
#define LT_S1_FLOOR_RAISE_TO_8_BELLOW_LOWEST_CEILING_CRUSHES 55
#define LT_WR_FLOOR_RAISE_TO_8_BELLOW_LOWEST_CEILING_CRUSHES 94
#define LT_W1_FLOOR_RAISE_TO_8_BELLOW_LOWEST_CEILING_CRUSHES 56
#define LT_SR_FLOOR_LOWER_TO_HIGHEST_FLOOR 45
#define LT_S1_FLOOR_LOWER_TO_HIGHEST_FLOOR 102
#define LT_WR_FLOOR_LOWER_TO_HIGHEST_FLOOR 83
#define LT_W1_FLOOR_LOWER_TO_HIGHEST_FLOOR 19
#define LT_SR_FLOOR_LOWER_TO_8_ABOVE_HIGHEST_FLOOR 70
#define LT_S1_FLOOR_LOWER_TO_8_ABOVE_HIGHEST_FLOOR 71
#define LT_WR_FLOOR_LOWER_TO_8_ABOVE_HIGHEST_FLOOR 98
#define LT_W1_FLOOR_LOWER_BY_8_ABOVE_HIGHEST_FLOOR 36
#define LT_WR_FLOOR_RAISE_BY_24 92
#define LT_W1_FLOOR_RAISE_BY_24 58
#define LT_WR_FLOOR_RAISE_BY_24_CHANGES_TEXTURE 93
#define LT_W1_FLOOR_RAISE_BY_24_CHANGES_TEXTURE 59
#define LT_WR_FLOOR_RAISE_BY_SHORTEST_LOWER_TEXTURE 96
#define LT_W1_FLOOR_RAISE_BY_SHORTEST_LOWER_TEXTURE 30
#define LT_S1_FLOOR_RAISE_BY_512 140

// Ceiling types
#define LT_SR_CEILING_LOWER_TO_FLOOR 43
#define LT_S1_CEILING_LOWER_TO_FLOOR 41
#define LT_W1_CEILING_RAISE_TO_HIGHEST_CEILING 40
#define LT_WR_CEILING_LOWER_TO_8_ABOVE_FLOOR 72
#define LT_W1_CEILING_LOWER_TO_8_ABOVE_FLOOR 44

// Platform types
#define LT_SR_FLOOR_RAISE_BY_24_CHANGES_TEXTURE 66
#define LT_S1_FLOOR_RAISE_BY_24_CHANGES_TEXTURE 15
#define LT_SR_FLOOR_RAISE_BY_32_CHANGES_TEXTURE 67
#define LT_S1_FLOOR_RAISE_BY_32_CHANGES_TEXTURE 14
#define LT_SR_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_CHANGES_TEXTURE 68
#define LT_S1_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_CHANGES_TEXTURE 20
#define LT_WR_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_CHANGES_TEXTURE 95
#define LT_W1_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_CHANGES_TEXTURE 22
#define LT_G1_FLOOR_RAISE_TO_NEXT_HIGHER_FLOOR_CHANGES_TEXTURE 47
#define LT_WR_FLOOR_START_MOVING_UP_AND_DOWN 87
#define LT_W1_FLOOR_START_MOVING_UP_AND_DOWN 53
#define LT_WR_FLOOR_STOP_MOVING 89
#define LT_W1_FLOOR_STOP_MOVING 54
#define LT_SR_LIFT_LOWER_WAIT_RAISE 62
#define LT_S1_LIFT_LOWER_WAIT_RAISE 21
#define LT_WR_LIFT_LOWER_WAIT_RAISE_ALSO_MONSTERS 88
#define LT_W1_LIFT_LOWER_WAIT_RAISE 10
#define LT_SR_LIFT_LOWER_WAIT_RAISE_FAST 123
#define LT_S1_LIFT_LOWER_WAIT_RAISE_FAST 122
#define LT_WR_LIFT_LOWER_WAIT_RAISE_FAST 120
#define LT_W1_LIFT_LOWER_WAIT_RAISE_FAST 121

// Crusher types
#define LT_S1_CEILING_LOWER_TO_8_ABOVE_FLOOR_PERPETUAL_SLOW_CHRUSHER_DAMAGE 49
#define LT_WR_CRUSHER_START_WITH_SLOW_DAMAGE 73
#define LT_W1_CRUSHER_START_WITH_SLOW_DAMAGE 25
#define LT_WR_CRUSHER_START_WITH_FAST_DAMAGE 77
#define LT_W1_CRUSHER_START_WITH_FAST_DAMAGE 6
#define LT_W1_CRUSHER_START_WITH_SLOW_DAMAGE_SILENT 141
#define LT_WR_CRUSHER_STOP 74
#define LT_W1_CRUSHER_STOP 57

// Stairs types
#define LT_S1_STAIRS_RAISE_BY_8 7
#define LT_W1_STAIRS_RAISE_BY_8 8
#define LT_S1_STAIRS_RAISE_BY_16_FAST 127
#define LT_W1_STAIRS_RAISE_BY_16_FAST 100

// Lighting types
#define LT_SR_LIGHT_CHANGE_TO_35 139
#define LT_WR_LIGHT_CHANGE_TO_35 79
#define LT_W1_LIGHT_CHANGE_TO_35 35
#define LT_SR_LIGHT_CHANGE_TO_255 138
#define LT_WR_LIGHT_CHANGE_TO_255 81
#define LT_W1_LIGHT_CHANGE_TO_255 13
#define LT_WR_LIGHT_CHANGE_TO_BRIGHTEST_ADGACENT 80
#define LT_W1_LIGHT_CHANGE_TO_BRIGHTEST_ADJACENT 12
#define LT_W1_LIGHT_CHANGE_TO_DARKEST_ADJACENT 104
#define LT_W1_LIGHT_START_BLINKING 17

// Exit types
#define LT_S1_EXIT_LEVEL 11
#define LT_W1_EXIT_LEVEL 52
#define LT_S1_EXIT_LEVEL_GOES_TO_SECRET_LEVEL 51
#define LT_W1_EXIT_LEVEL_GOES_TO_SECRET_LEVEL 124

// Teleporter types
#define LT_WR_TELEPORT_ALSO_MONSTERS 97
#define LT_W1_TELEPORT_ALSO_MONSTERS 39
#define LT_WR_TELEPORT_MONSTERS_ONLY 126
#define LT_W1_TELEPORT_MONSTERS_ONLY 125

// Donut types
#define LT_S1_FLOOR_RAISE_DONUT_CHANGES_TEXTURE 9

// Animated textures
#define LT_SCROLL_TEXTURE_LEFT 48
